language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.2 # because Trusty version is 1.0.x which is EXTREMELY outdated

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=linux LAZ_OPT="--os=linux --cpu=x86_64"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./travis-lazarus/.travis.install.py

script:
  - lazbuild $LAZ_OPT VecDraw.lpi  # Build project
  - "if [[ $LAZ_ENV = "linux" && -d "./VecDraw" ]]; then 
    mv ./VecDraw ./VecDraw_build; 
    elif [[ $LAZ_ENV = "wine" && -d "./VecDraw.exe" ]]; then
    mv ./VecDraw.exe ./VecDraw_build.exe; 
    fi"
  - zip VecDraw_build.zip -r -5 ./icons/* ./VecDraw_build*

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "VecDraw_build.zip"
#   skip_cleanup: true
#   on:
#     tags: true

notifications:
  email:
    on_success: false
    on_failure: change